void Interpreter();
int analizerAndExtractor();
void readCharacter();
void clearBuffer();
int recognizeExpression();
int recognizeTerm();
int recognizeFactor();
int recognizeNumber();
char recognizeDigit();
signed char recognizeAdditiveOperator();
signed char recognizeMultiplicativeOperator();
char recognizeParenthese();